### ISSUE TITLE
exceptions must derive from BaseException

### ISSUE THREAD

**Issue by robvanderg** [danielvarab/uniparse#9]
your error message is not an "exception": 

Traceback (most recent call last):
  File "/home/robv/data_size/uniparse/uniparse/model.py", line 19, in <module>
    import uniparse.decoders as decoders
  File "/home/robv/data_size/uniparse/uniparse/decoders/__init__.py", line 2, in <module>
    from uniparse.decoders.eisner import Eisner as eisner
ModuleNotFoundError: No module named 'uniparse.decoders.eisner'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_pytorch_kiperwasser.py", line 6, in <module>
    from uniparse.callbacks import ModelSaveCallback
  File "/home/robv/data_size/uniparse/uniparse/__init__.py", line 4, in <module>
    from uniparse.model import Model
  File "/home/robv/data_size/uniparse/uniparse/model.py", line 21, in <module>
    raise ERROR_MSG

**Comment by danielvarab** [comment]
resolved in #11
